apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hms-secrets
type: Opaque
data:
  username: {{ .Values.app.secrets.username | quote }}
  password: {{ .Values.app.secrets.password | quote }}
