apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive-metastore.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hive-metastore.labels" . | nindent 4 }}
data:
  hive-site.xml: |
    {{ .Values.hiveSiteXml | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive-metastore.fullname" . }}-2
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hive-metastore.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.app.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}