image:
  repository: 868073499690.dkr.ecr.us-east-2.amazonaws.com/hive-metastore

  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 9083

ingress:
  enabled: false
  annotations: {}
  hosts: 
    - host: localhost
      paths: /hive-metastore

replicaCount: 1

app:
  env:
    METASTORE_TYPE: "postgres"
    METASTORE_DB_HOSTNAME: "m360-devk-db2-cluster.cluster-cuviup6iq5tv.us-east-2.rds.amazonaws.com"
    HIVE_CONF_DIR: "/opt/hive-configs"
  secrets:
    username: bTM2MGFwcA==    # base64 encoded username
    password: d0dyOGNwZzFjRmZK   # base64 encoded password

hiveSiteXml: |
  <configuration>
      <property>
      <name>fs.s3.impl</name>
      <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
    </property>
    <property>
      <name>fs.s3a.impl</name>
      <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
    </property>
    <property>
        <name>metastore.thrift.uris</name>
        <value>thrift://hive-metastore:9083</value>
        <description>Thrift URI for the remote metastore. Used by metastore client to connect to remote metastore.</description>
    </property>
    <property>
        <name>metastore.task.threads.always</name>
        <value>org.apache.hadoop.hive.metastore.events.EventCleanerTask,org.apache.hadoop.hive.metastore.MaterializationsCacheCleanerTask</value>
    </property>
    <property>
        <name>metastore.expression.proxy</name>
        <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://m360-devk-db2-cluster.cluster-cuviup6iq5tv.us-east-2.rds.amazonaws.com:5432/metastore_db</value>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>CUserPlaceholder</value>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>CPPlaceholder</value>
    </property>
    <property>
        <name>fs.s3a.endpoint</name>
        <value>https://s3.us-east-2.amazonaws.com</value>
    </property>
    <property>
        <name>fs.s3a.path.style.access</name>
        <value>false</value>
    </property>
  </configuration>

